### ISSUE TITLE
Extra security ?

### ISSUE THREAD

**Issue by romquenin** [tirtadji-com/rpi_debian_ha_supervised#1]
Hello @ranrinc, first of all i would like to thank you for sharing this simplified config. I was looking for a way to install HA Supervised and your contribution helped me a lot.
I have followed the guide on https://krdesigns.com/ and Home Assistant Supervised works perfectly.
Could you please tell me what type of extra security this config (from github) add to the installation.
Thank you for your help.

**Comment by ranrinc** [comment]
Its install Fail2Ban, SSH Key, and extra setting on NGINX sites. Which needed to complete the enhancement. You can check my script one by one if needed. Please also let me know if you find bugs, so I can fix them. Furthermore, it automatically installs Portainer which can be accessed via IP:PORT 9000. This way you can see if your docker is having a problem.

**Comment by romquenin** [comment]
Thanks for the reply. I have another question.
At step 5 i don't need to add the SSH password, i'm directly logged-in after the command: `ssh root@myipadress`
I have created the public ssh keys on my windows machine with the command line: `ssh-keygen`
Unfortunately after editing the `sysconf.txt` file, i'm only able to connect to the the Pi in SSH from the PC's terminal, not from Putty or the Mac's terminal (i receive the error: `Permission denied (publickey,password))`.
Do you know why i can't login remotly from a different device with the SSH password ?
Thank you for your help.

**Comment by ranrinc** [comment]
> Thanks for the reply. I have another question.
> At step 5 i don't need to add the SSH password, i'm directly logged-in after the command: `ssh root@myipadress`
> I have created the public ssh keys on my windows machine with the command line: `ssh-keygen`
> Unfortunately after editing the `sysconf.txt` file, i'm only able to connect to the the Pi in SSH from the PC's terminal, not from Putty or the Mac's terminal (i receive the error: `Permission denied (publickey,password))`.
> Do you know why i can't login remotly from a different device with the SSH password ?
> Thank you for your help.

Simple answer, the reason you cant connect to your RPI from other terminal because SSH will check your private keys. In your case you need to copy those private keys to your other computer so it will allow you to connect. Or you can create new key and then add each public key to your RPI by add the public key into .ssh/authorized_keys
