### ISSUE TITLE
Influx Install Script

### ISSUE THREAD

**Issue by Victripper** [tirtadji-com/rpi_debian_ha_supervised#3]
I run in to an issue with the install script for influxdb. I tried to run the create for the config file and got the same outcome.

I would ideally like to have this config file outside the docker so I can modify it as per usual and add in http access to influx

```
root@Home-AssistantDebian:~/docker# ./influxdb-install.sh 
Error: unknown command "config" for "influxd"
See 'influxd -h' for help
WARNING: Published ports are discarded when using host network mode
7bac7580728eea178337bcc267dd2c854bdf08d929215a1e42fefade0af29ab1
InfluxDB installed [DONE]


#!/bin/bash
###############################################################
#	Created by Richard Tirtadji
#   Auto installer for Raspberry on Debian 11 + HA Supervised  
#  Install Docker InFlux DB
###############################################################
# open port 8006 for HA
#ufw allow 8006
#service ufw restart

# Making Directory for docker container
mkdir /etc/influxdb 
mkdir /usr/share/hassio/docker/influxdb

# Install influxdb
docker run --rm influxdb influxd config | tee /etc/influxdb/influxdb.conf > /dev/null
docker run -d -p 8086:8086 --restart=always --net=host --name="influxdb" -v /etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf -v /usr/share/hassio/docker/influxdb:/var/lib/influxdb influxdb -config /etc/influxdb/influxdb.conf

echo -e "InfluxDB installed \e[32m[DONE]\033[0m"
```

**Comment by ranrinc** [comment]
Gimme some time, I believe that the script also needs to update since influxdb 1.0 and influxdb 2.0 are different. I believe MQTT will also require a new update since it's quite different.

**Comment by Victripper** [comment]
Thanks, I have installed an older version of influxdb 1.8.6 for now and happy with the setup as all works apart not having the access to modify the config file within the container to enable http etc.

**Comment by ranrinc** [comment]
A beta is now completely finished and redesign, just need some time to update my repo for a release. Make some major changes on NGINX by replacing it with NGINX Proxy Manager, adding MySQL to the list, and adding influxDB 2.0 which I think is much better than influxDB 1.0.
