### ISSUE TITLE
Uninstall HA Supervisor cleanly to do a new install

### ISSUE THREAD

**Issue by Victripper** [tirtadji-com/rpi_debian_ha_supervised#5]
I wasn't thinking when I installed watchtower which HA doesn't like to now I have an unhealthy system.  I went through an old process and got rid of HA that I know of but when I reinstall it comes up with my old setup and still has the issue.

Is it possible to provide a clean removal script?

**Comment by ranrinc** [comment]
My advice is just to backup your HA and do the entire system and restore the rest. Using restore should be a brezze

**Comment by Victripper** [comment]
Got it sorted by deleting all images in portainer. When I did a reinstall it went back to unhealthy

**Comment by ranrinc** [comment]
I guess you solve the problem,so I can close this issue?
